name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.1.1
  
  # Firebase dependencies
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add assets
  assets:
    - assets/images/
    - assets/images/collections/clothing.jpg
    - assets/images/collections/merchandise.jpg
    - assets/images/collections/graduation.jpg
    - assets/images/collections/personalisation.jpg
    - assets/images/collections/print_shack.jpg
    - assets/images/collections/portsmouth.jpg
    - assets/images/collections/pride.jpg
    - assets/images/collections/stationery.jpg
    - assets/images/collections/sports.jpg
    - assets/images/hoodie_purple.jpg
    - assets/images/tshirt_signature.jpg
    - assets/images/tote_bag.jpg